In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
import pandas as pd
data = pd.DataFrame(data=iris.data , columns=iris.feature_names)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
data['flower'] = iris.target
data.head()

# here we need to put the flower name instead of number 
data['flower'] = data['flower'].apply(lambda x: iris.target_names[x])
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data , iris.target , test_size = 0.25 )

# SVM Model 

In [14]:
# here the hyper parameter tuning is the way to choose the best parameter for the model 

In [16]:
from sklearn.svm import SVC 
model = SVC(kernel='rbf' , C=30 , gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9736842105263158

In [17]:
# now import the cross_val_score for the Kfold 
from sklearn.model_selection import cross_val_score

In [20]:
# try the cross val score for the svm model 
# the first one have this attribute with K = 5
cross_val_score(SVC(kernel='linear' , C=30 , gamma='auto') , iris.data , iris.target , cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [21]:
# try the cross val score for the svm model 
# the first one have this attribute with K = 5
cross_val_score(SVC(kernel='rbf' , C=30 , gamma='auto') , iris.data , iris.target , cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [27]:
# try the cross val score for the svm model 
# the first one have this attribute with K = 5
cross_val_score(SVC(kernel='sigmoid' , C=30 , gamma='auto') , iris.data , iris.target , cv=5)

array([0.33333333, 0.1       , 0.        , 0.03333333, 0.        ])

In [28]:
# try the cross val score for the svm model 
# the first one have this attribute with K = 5
cross_val_score(SVC(kernel='poly' , C=30 , gamma='auto') , iris.data , iris.target , cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [29]:
# here we make a different attribute we can calculate the average of the score to know what is the best 
# parameter for our model 

In [30]:
import numpy as np

In [31]:
# here we make a loop  for simplify 
kernal_val = ['rbf' , 'linear' , 'poly']     # you can try all values 
C_val = [10,20,30]
average_score = {}    # this dictationary for store the avg_score for each Kernal Type 

for kv in kernal_val:
    for cv in C_val:
        score = cross_val_score(SVC(kernel=kv , C= cv , gamma='auto') , iris.data , iris.target , cv=5)
        average_score[kv + '_' + str(cv)] =  np.average(score)    # calculate the average score for each kernal value and store it 

In [32]:
# this is the values 
average_score

{'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96,
 'poly_10': 0.9666666666666666,
 'poly_20': 0.9533333333333334,
 'poly_30': 0.9533333333333334}

# note the for loop above we can do the same thing with 
# GridSearchCV

In [36]:
from sklearn.model_selection import GridSearchCV

In [39]:
# craete the gridSearchCv Object
clf = GridSearchCV( SVC(gamma='auto'), {
    'C':[10,20,30,40],
    'kernel':['rbf','linear','poly']
}, cv=5 , return_train_score = False )

# now train the model 
clf.fit(iris.data , iris.target)
clf.cv_results_


{'mean_fit_time': array([0.00159831, 0.00139828, 0.00479431, 0.00099835, 0.00059943,
        0.00739264, 0.00099931, 0.00079927, 0.00839171, 0.00079927,
        0.00079927, 0.00839243]),
 'std_fit_time': array([4.89941894e-04, 4.88560669e-04, 2.56042420e-03, 1.24891289e-06,
        4.89434179e-04, 6.36873851e-03, 8.06404806e-07, 3.99637265e-04,
        6.30598477e-03, 3.99637265e-04, 3.99637237e-04, 6.70567076e-03]),
 'mean_score_time': array([0.0007988 , 0.00079927, 0.0006001 , 0.00019984, 0.00039959,
        0.00020003, 0.00039968, 0.00019984, 0.00040069, 0.00039964,
        0.00019979, 0.00039959]),
 'std_score_time': array([0.0003994 , 0.00074708, 0.00048998, 0.00039968, 0.0004894 ,
        0.00040007, 0.00048951, 0.00039968, 0.00049074, 0.00048945,
        0.00039959, 0.0004894 ]),
 'param_C': masked_array(data=[10, 10, 10, 20, 20, 20, 30, 30, 30, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False

In [41]:
# to easly read the above results do this
df = pd.DataFrame(clf.cv_results_)
df

# some notes 
# splits from 0 to 4 is the K fold number we provided
# rank_test_score is show you what is the best parameter 
# mean_test_score is the average score for this parameter in each cross validation 

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.001598  4.899419e-04         0.000799        0.000399      10   
1        0.001398  4.885607e-04         0.000799        0.000747      10   
2        0.004794  2.560424e-03         0.000600        0.000490      10   
3        0.000998  1.248913e-06         0.000200        0.000400      20   
4        0.000599  4.894342e-04         0.000400        0.000489      20   
5        0.007393  6.368739e-03         0.000200        0.000400      20   
6        0.000999  8.064048e-07         0.000400        0.000490      30   
7        0.000799  3.996373e-04         0.000200        0.000400      30   
8        0.008392  6.305985e-03         0.000401        0.000491      30   
9        0.000799  3.996373e-04         0.000400        0.000489      40   
10       0.000799  3.996372e-04         0.000200        0.000400      40   
11       0.008392  6.705671e-03         0.000400        0.000489      40   

   param_kernel                         params  split0_test_score  \
0           rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
1        linear  {'C': 10, 'kernel': 'linear'}           1.000000   
2          poly    {'C': 10, 'kernel': 'poly'}           1.000000   
3           rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
4        linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5          poly    {'C': 20, 'kernel': 'poly'}           0.966667   
6           rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
7        linear  {'C': 30, 'kernel': 'linear'}           1.000000   
8          poly    {'C': 30, 'kernel': 'poly'}           0.966667   
9           rbf     {'C': 40, 'kernel': 'rbf'}           1.000000   
10       linear  {'C': 40, 'kernel': 'linear'}           1.000000   
11         poly    {'C': 40, 'kernel': 'poly'}           0.966667   

    split1_test_score  split2_test_score  split3_test_score  \
0            1.000000           0.966667           0.966667   
1            1.000000           0.900000           0.966667   
2            1.000000           0.900000           0.933333   
3            1.000000           0.900000           0.966667   
4            1.000000           0.900000           0.933333   
5            0.966667           0.900000           0.933333   
6            1.000000           0.900000           0.933333   
7            1.000000           0.900000           0.900000   
8            0.966667           0.900000           0.933333   
9            0.966667           0.900000           0.933333   
10           1.000000           0.900000           0.900000   
11           0.966667           0.900000           0.933333   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 1.0         0.980000        0.016330                1  
1                 1.0         0.973333        0.038873                2  
2                 1.0         0.966667        0.042164                4  
3                 1.0         0.966667        0.036515                3  
4                 1.0         0.966667        0.042164                4  
5                 1.0         0.953333        0.033993               10  
6                 1.0         0.960000        0.038873                6  
7                 1.0         0.960000        0.048990                6  
8                 1.0         0.953333        0.033993               10  
9                 1.0         0.960000        0.038873                6  
10                1.0         0.960000        0.048990                6  
11                1.0         0.953333        0.033993               10

In [43]:
# simplify the above table 
df[['param_C' , 'param_kernel' , 'mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       10         poly         0.966667
3       20          rbf         0.966667
4       20       linear         0.966667
5       20         poly         0.953333
6       30          rbf         0.960000
7       30       linear         0.960000
8       30         poly         0.953333
9       40          rbf         0.960000
10      40       linear         0.960000
11      40         poly         0.953333

In [44]:
# if you need to know the properties of the clf 
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [45]:
# you can choose from them like this 
clf.best_score_

0.9800000000000001

In [46]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [52]:
# the randomizesearch cv is used for make a random iteration
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV( SVC(gamma='auto'), {
    'C':[10,20,30,40],
    'kernel':['rbf','linear','poly']
}, cv=5 , return_train_score = False  , n_iter=2)

# now train the model 
rs.fit(iris.data , iris.target)
df = pd.DataFrame(rs.cv_results_)
df[['param_C' , 'param_kernel' , 'mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1      40          rbf         0.960000

In [53]:
# the above code make 2 iteration 
# when you run it every time give you random results 
